### ISSUE TITLE
.netstandard build

### ISSUE THREAD

**Issue by jackbond** [hps/heartland-dotnet#10]
It's great that you guys have this code available on GitHub. Are there any plans to update this to be a .netstandard library so that it could be run with .netcore and on non-windows platforms?

**Comment by slogsdon** [comment]
HI @jackbond!

We don't have any current plans to update this SDK to be compatible with `netstandard*` targets.

That being said, we are building a more generic Global Payments SDK (we're a part of GP) that connects to our payment gateway and other APIs as well as other entities within the GP organization. This new Global Payments SDK (https://github.com/globalpayments/dotnet-sdk) targets `netstandard1.3` and can be used in .NET Framework v4.6+ projects as well as .NET Core v1.0+ projects and can be added to your project via Nuget as `GlobalPayments.Api` with the prerelease flag set. More documentation on its use can be found on our developer portal: https://developer.heartlandpaymentsystems.com/Documentation/introduction/.

Let us know if you have any questions/concerns.

**Comment by jackbond** [comment]
Hi @slogsdon,

Any idea when GlobalPayments.Api will be out of preview?

**Comment by slogsdon** [comment]
@jackbond We published a new [Nuget version of GlobalPayments.Api](https://www.nuget.org/packages/GlobalPayments.Api/1.0.20) this morning that removes the prerelease flag.
