### ISSUE TITLE
Solution does not compile

### ISSUE THREAD

**Issue by andreymir** [hps/heartland-dotnet#2]
Getting the error on solution build:

Error   1   This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\heartland\heartland-dotnet\.nuget\NuGet.targets.   C:\heartland\heartland-dotnet\SecureSubmit\SecureSubmit.csproj  224 5   SecureSubmit

Seems like the issue is that .nuget directory is missing in the repository.

**Comment by slogsdon** [comment]
Hi @andreymir! If you enable Package Restore on the solution as the error suggests, are you still unable to compile the solution? This should be the route we take internally, so let me know if this doesn't help your issue.

**Comment by andreymir** [comment]
Yes, it does help. It creates `.nuget` folder and after that the solution compiles. However, I would prefer  `.nuget` directory exists in the repository, so this extra step would be unnecessary.

**Comment by securesubmit-buildmaster** [comment]
Hi Andrey,

We have specifically left this out to allow people to manage their own nuget packages.

Thanks,

[colorline]

Russell Everett
Senior Developer
Payment Processing, Payroll Solutions and Rewards
P: (812) 280-8222 x65622
One Heartland Way
Jeffersonville, IN 47130
HeartlandPaymentSystems.comhttp://www.heartlandpaymentsystems.com/   facebook.comhttp://www.facebook.com/HeartlandHPY/
[Heartland Payment Systems]http://www.heartlandpaymentsystems.com/
CONFIDENTIALITY WARNING: This email may contain privileged or confidential information and is for the
sole use of the intended recipient(s). Any unauthorized use or disclosure of this communication is prohibited.
If you believe that you have received this email in error, please notify the sender immediately and delete it from
your system.
