### ISSUE TITLE
PaxTcpInterface leaves a thread running even after being disposed

### ISSUE THREAD

**Issue by jorupp** [hps/heartland-dotnet#6]
https://github.com/hps/heartland-dotnet/blob/0fb35f8e4b108e521bfcf4e712c5e1fa8e798a55/SecureSubmit/Terminals/PAX/Interfaces/PaxTcpInterface.cs#L27
My app is planning to create a new instance of this rather frequently, and it's leaving a lot of threads running in `PaxTcpInterface`.  Is there a reason this thread doesn't exit when the `PaxTcpInterface` is disposed?  Also, shouldn't a thread like this be run with `IsBackground=true` (to avoid blocking the process from exiting)?

**Comment by russelleverett** [comment]
This is an issue we corrected in our latest version SDK. I am back porting this fix to this version of the SDK and will release a fix within the week,

**Comment by jorupp** [comment]
Is there a later version of the SDK we could be using?  I thought this codebase was 2.11.1, which looks like the latest version on the Nuget gallery as well.
